# Generated by Django 5.2 on 2025-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], max_length=50),
        ),
    ]
