# Generated by Django 5.2 on 2025-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_job_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_shift', 'Night Shift'), ('day_shift', 'Day Shift')], default='Unknown Company', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Unknown Title', max_length=255),
            preserve_default=False,
        ),
    ]
